compressionLevel: 9

enableGlobalCache: false

enableOfflineMode: true

nodeLinker: node-modules

supportedArchitectures:
  cpu:
    - x64
    - arm64
  os:
    - darwin
    - linux
    - win32

yarnPath: .yarn/releases/yarn-4.9.1-git.20250509.hash-dc73e88.cjs
