compressionLevel: 9

enableGlobalCache: false

enableImmutableCache: false

enableNetwork: true

enableOfflineMode: false

nodeLinker: node-modules

supportedArchitectures:
  cpu:
    - x64
    - arm64
  os:
    - darwin
    - linux
    - win32

yarnPath: .yarn/releases/yarn-4.9.1-git.20250510.hash-bee82ef.cjs
