name: Test and check
on:
  push:

jobs:
  test:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        node-version: [20, 22]
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.8.0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Syncpack lint
        run: pnpm syncpack lint
      - name: Run linter
        run: pnpm check:turbo
      - name: Run linter (formatting)
        run: pnpm check:format
      - name: Run tests
        run: pnpm test
